# Save this block and apply it: kubectl apply -f ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: azure-k8s-site-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: azure-site.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: azure-k8s-site-service
            port:
              number: 80